@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Feb 13 08:24:30 +0100 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_Dflipflop_behav -key {Behavioral:sim_1:Functional:tb_Dflipflop} -tclbatch tb_Dflipflop.tcl -view C:/Users/erik/IES_codebase/programming_reliable_systems/Labs/Lab3/lab3_step1/tb_Dflipflop_behav.wcfg -log simulate.log"
call xsim  tb_Dflipflop_behav -key {Behavioral:sim_1:Functional:tb_Dflipflop} -tclbatch tb_Dflipflop.tcl -view C:/Users/erik/IES_codebase/programming_reliable_systems/Labs/Lab3/lab3_step1/tb_Dflipflop_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
